### ISSUE TITLE
Missing "command" field in deploy request from UI when using custom executor

### ISSUE THREAD

**Issue by petrovicboban** [HubSpot/Singularity#1336]
Hi,  
When I try to deploy a task using singularity executor, iether with docker or mesos container, I face the same problem: task fails.  
  
With docker container, final error message is:  
**Failed to run docker container: Shell specified but no command value provided**  
  
and that's true, which can be seen in mesos slave logs:  
```
command {
  environment {
    variables {
      name: "INSTANCE_NO"
      value: "1"
    }
    variables {
      name: "TASK_HOST"
      value: "server2.stratagem.co"
    }
    variables {
      name: "TASK_REQUEST_ID"
      value: "test_req"
    }
    variables {
      name: "TASK_DEPLOY_ID"
      value: "20"
    }
    variables {
      name: "TASK_ID"
      value: "test_req-20-1478190498991-1-server2.stratagem.co-DEFAULT"
    }
    variables {
      name: "ESTIMATED_INSTANCE_COUNT"
      value: "1"
    }
  }
  shell: true
}
```

This is in  mesos/src/docker/docker.cpp
```
  if (commandInfo.shell()) {
    if (!commandInfo.has_value()) {
      return Failure("Shell specified but no command value provided");
    }
```
This is happening in singularity 0.11.0, also in 0.12.0  

  
Note:
I created a docker task in version 0.8.0 and when bounce it, this is in logs:  
```
  command {
    environment {
      variables {
        name: "INSTANCE_NO"
        value: "1"
      }
      variables {
        name: "TASK_HOST"
        value: "server2.stratagem.co"
      }
      variables {
        name: "TASK_REQUEST_ID"
        value: "docker"
      }
      variables {
        name: "TASK_DEPLOY_ID"
        value: "29"
      }
      variables {
        name: "TASK_ID"
        value: "docker-29-1478190371896-1-server2.stratagem.co-DEFAULT"
      }
      variables {
        name: "ESTIMATED_INSTANCE_COUNT"
        value: "1"
      }
    }
    value: "/usr/local/bin/singularity-executor"
  }
```
And it bounces successfuly.

When I try to deploy task, this is what I capture by tcpdump:
```
POST /singularity/api/deploys HTTP/1.1
Host: server.domain.com:7099
Connection: keep-alive
Content-Length: 383
accept: application/json
Origin: http://server.domain.com:7099
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/53.0.2785.143 Chrome/53.0.2785.143 Safari/537.36
content-type: application/json
Referer: http://server.domain.com:7099/singularity/request/test_req/deploy
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8,hr;q=0.6,sl;q=0.4,sr;q=0.2,ru;q=0.2

{"deploy":{"id":"23","executorType":"custom","containerInfo":{"type":"docker","docker":{"image":"ubuntu:14.04","network":"BRIDGE","parameters":{"hostname":"test"}}},"resources":{"cpus":0.1,"memoryMb":128},"executorData":{"cmd":"/usr/local/bin/singularity-executor","user":"root","sigKillProcessesAfterMillis":120000},"healthCheckProtocol":"HTTP","requestId":"test_req","shell":true}}
```
I wrote ```ping google.com``` in the field 'Command to Execute' on Deploy page, but I don't see it in the request, and that looks like the issue.

If I send this POST request mannualy, with included "command" : "ping google.com"  as field in deploy object, everything goes fine as expected.

**Comment by ssalinas** [comment]
Fixed in https://github.com/HubSpot/Singularity/pull/1341

**Comment by petrovicboban** [comment]
It's not resolved, still the same.
Custom executor does not handle command well, when deploy from gui.

**Comment by ssalinas** [comment]
@petrovicboban when trying this on my own machine it works for me. Since you can reproduce, can you please capture the json being sent for your deploy (e.g. via network tab in chrome dev tools). A screenshot of the corresponding parameters being put into the command fields int he ui would be helpful as well.

**Comment by petrovicboban** [comment]
Sure, I will do it tommorow.
I have to say that deploying manually, by posting jsons to API endpoint works well.

**Comment by petrovicboban** [comment]
I removed all requests, and start over, but this time it was all ok.
I don't know what was wrong, but it's important that it's solved.
Thanks for efforts.
